- name: Launch a t2 micro instance
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Launch instance
      local_action:
        module: ec2
        aws_secret_key: "{{ ansible_env.aws_secret_key }}"
        aws_access_key: "{{ ansible_env.aws_access_key }}"
        region: us-east-1
        keypair: testing
        group: testing
        instance_type: c3.2xlarge
        image: ami-123456
        wait: yes
        vpc_subnet_id: subnet-123456
        assign_public_ip: yes
      register: ec2

    - name: Add instances to securioty group
      local_action: add_host hostname= groupname=testing
      with_items: ec2.instances

    - name: Tag instances
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: testing
